## Introducción <a id='intro'></a>
Como analista de datos, tu trabajo consiste en analizar datos para extraer información valiosa y tomar decisiones basadas en ellos. Esto implica diferentes etapas, como la descripción general de los datos, el preprocesamiento y la prueba de hipótesis.

Siempre que investigamos, necesitamos formular hipótesis que después podamos probar. A veces aceptamos estas hipótesis; otras veces, las rechazamos. Para tomar las decisiones correctas, una empresa debe ser capaz de entender si está haciendo las suposiciones correctas.

En este proyecto, compararás las preferencias musicales de las ciudades de Springfield y Shelbyville. Estudiarás datos reales de transmisión de música online para probar la hipótesis a continuación y comparar el comportamiento de los usuarios y las usuarias de estas dos ciudades.

### Objetivo:
Prueba la hipótesis:
1. La actividad de los usuarios y las usuarias difiere según el día de la semana y dependiendo de la ciudad.


### Etapas
Los datos del comportamiento del usuario se almacenan en el archivo `/datasets/music_project_en.csv`. No hay ninguna información sobre la calidad de los datos, así que necesitarás examinarlos antes de probar la hipótesis.

Primero, evaluarás la calidad de los datos y verás si los problemas son significativos. Entonces, durante el preprocesamiento de datos, tomarás en cuenta los problemas más críticos.



## Descripción de los datos <a id='data_review'></a>

Abrir datos y examínalos.

In [1]:
# Importar pandas
import pandas as pd


In [2]:
# Leer el archivo y almacenarlo en df
df=pd.read_csv('music_project_en.csv')

In [3]:
# Obtener las 10 primeras filas de la tabla df
df.head(10)


userID                        Track            artist   genre  \
0  FFB692EC            Kamigata To Boots  The Mass Missile    rock   
1  55204538  Delayed Because of Accident  Andreas Rönnberg    rock   
2    20EC38            Funiculì funiculà       Mario Lanza     pop   
3  A3DD03C9        Dragons in the Sunset        Fire + Ice    folk   
4  E2DC1FAE                  Soul People        Space Echo   dance   
5  842029A1                       Chains          Obladaet  rusrap   
6  4CB90AA5                         True      Roman Messer   dance   
7  F03E1C1F             Feeling This Way   Polina Griffith   dance   
8  8FA1D3BE                     L’estate       Julia Dalia  ruspop   
9  E772D5C0                    Pessimist               NaN   dance   

        City        time        Day  
0  Shelbyville  20:28:33  Wednesday  
1  Springfield  14:07:09     Friday  
2  Shelbyville  20:58:07  Wednesday  
3  Shelbyville  08:37:09     Monday  
4  Springfield  08:34:34     Monday  
5  Shelbyville  13:09:41     Friday  
6  Springfield  13:00:07  Wednesday  
7  Springfield  20:47:49  Wednesday  
8  Springfield  09:17:40     Friday  
9  Shelbyville  21:20:49  Wednesday

Información general sobre la tabla

In [4]:
# Obtener la información general sobre nuestros datos

df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65079 entries, 0 to 65078
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0     userID  65079 non-null  object
 1   Track     63736 non-null  object
 2   artist    57512 non-null  object
 3   genre     63881 non-null  object
 4     City    65079 non-null  object
 5   time      65079 non-null  object
 6   Day       65079 non-null  object
dtypes: object(7)
memory usage: 3.5+ MB


Observaciones sobre la tabla. Contiene siete columnas. Almacenan los mismos tipos de datos: `object`.

Según la documentación:
- `' userID'`: identificador del usuario o la usuaria;
- `'Track'`: título de la canción;
- `'artist'`: nombre del artista;
- `'genre'`: género de la pista;
- `'City'`: ciudad del usuario o la usuaria;
- `'time'`: la hora exacta en la que se reprodujo la canción;
- `'Day'`: día de la semana.

Podemos ver tres problemas con el estilo en los encabezados de la tabla:
1. Algunos encabezados están en mayúsculas, otros en minúsculas.
2. Hay espacios en algunos encabezados.
3. Existen valores nulos en las columnas genre artist y track

### Observaciones: <a id='data_review_conclusions'></a>


* User es un codigo alfanumerico para cada usuario
* Track es un string
* Artist es un string
* Genre es un string
* City es un string
* Time es un numero con el formato Time
* Day es un string

* Es posible un análisis a partir de los datos proporcionados


## Preprocesamiento de datos <a id='data_preprocessing'></a>

El objetivo aquí es preparar los datos para que sean analizados.
El primer paso es resolver cualquier problema con los encabezados. Luego podemos avanzar a los valores ausentes y duplicados.


### Estilo del encabezado <a id='header_style'></a>

In [5]:
# Nombres de las columnas

df.columns


Index(['  userID', 'Track', 'artist', 'genre', '  City  ', 'time', 'Day'], dtype='object')

Acciones a realizar: 
* Todos los caracteres deben ser minúsculas.
* Eliminar los espacios.
* Si el nombre tiene varias palabras, utiliza snake_case.

In [6]:
# Encabezados poniendo todo en minúsculas

df.columns = df.columns.str.lower()
print(df.columns)


Index(['  userid', 'track', 'artist', 'genre', '  city  ', 'time', 'day'], dtype='object')


In [7]:
# Encabezados eliminando los espacios
df.columns = df.columns.str.strip().str.replace(' ', '')
print(df.columns)


Index(['userid', 'track', 'artist', 'genre', 'city', 'time', 'day'], dtype='object')


In [8]:
# Cambiar el nombre de la columna "userid"
new ={
    'userid':'user_id',
   
    }
df=df.rename(columns = new)

print(df.columns)  

Index(['user_id', 'track', 'artist', 'genre', 'city', 'time', 'day'], dtype='object')


In [9]:
# Comprobar el resultado: la lista de encabezados
print(df.columns) 

Index(['user_id', 'track', 'artist', 'genre', 'city', 'time', 'day'], dtype='object')


### Valores ausentes <a id='missing_values'></a>


In [10]:
# Calcular el número de valores ausentes

print(df.isna().sum())


user_id       0
track      1343
artist     7567
genre      1198
city          0
time          0
day           0
dtype: int64


In [11]:
# Bucle en los encabezados reemplazando los valores ausentes con 'unknown'

replace = ['track', 'artist' , 'genre']

for i in df.columns:

    df[i] = df[i].fillna('unknown')



In [12]:
# Contar valores ausentes
print(df.isna().sum())


user_id    0
track      0
artist     0
genre      0
city       0
time       0
day        0
dtype: int64


### Duplicados <a id='duplicates'></a>


In [13]:
# Contar duplicados explícitos

print(df.duplicated().sum())

3826


In [14]:
# Eliminar duplicados explícitos
print(df.drop_duplicates(inplace=True))

None


In [15]:
# Comprobar de nuevo si hay duplicados

print(df.duplicated().sum())


0


In [16]:
# Inspeccionar los nombres de géneros únicos
print(df['genre'].unique())
print(df['genre'].nunique())

['rock' 'pop' 'folk' 'dance' 'rusrap' 'ruspop' 'world' 'electronic'
 'unknown' 'alternative' 'children' 'rnb' 'hip' 'jazz' 'postrock' 'latin'
 'classical' 'metal' 'reggae' 'triphop' 'blues' 'instrumental' 'rusrock'
 'dnb' 'türk' 'post' 'country' 'psychedelic' 'conjazz' 'indie'
 'posthardcore' 'local' 'avantgarde' 'punk' 'videogame' 'techno' 'house'
 'christmas' 'melodic' 'caucasian' 'reggaeton' 'soundtrack' 'singer' 'ska'
 'salsa' 'ambient' 'film' 'western' 'rap' 'beats' "hard'n'heavy"
 'progmetal' 'minimal' 'tropical' 'contemporary' 'new' 'soul' 'holiday'
 'german' 'jpop' 'spiritual' 'urban' 'gospel' 'nujazz' 'folkmetal'
 'trance' 'miscellaneous' 'anime' 'hardcore' 'progressive' 'korean'
 'numetal' 'vocal' 'estrada' 'tango' 'loungeelectronic' 'classicmetal'
 'dubstep' 'club' 'deep' 'southern' 'black' 'folkrock' 'fitness' 'french'
 'disco' 'religious' 'hiphop' 'drum' 'extrememetal' 'türkçe'
 'experimental' 'easy' 'metalcore' 'modern' 'argentinetango' 'old' 'swing'
 'breaks' 'eurofolk' 

Duplicados implícitos:
* `hip`
* `hop`
* `hip-hop`


In [17]:
# Función para reemplazar duplicados implícitos

def replace_wrong_genres(a,b):
    
    
    for i in df['genre']:
        
        df['genre']=df['genre'].replace(a,b)
     
  
        

In [18]:
# Eliminar duplicados implícitos
wrong_genres= ['hip','hop','hip-hop']       
correct_genre='hiphop'

replace_wrong_genres(wrong_genres,correct_genre)


In [19]:
# Comprobación de duplicados implícitos
print(df['genre'].unique())
print(df['genre'].nunique())


['rock' 'pop' 'folk' 'dance' 'rusrap' 'ruspop' 'world' 'electronic'
 'unknown' 'alternative' 'children' 'rnb' 'hiphop' 'jazz' 'postrock'
 'latin' 'classical' 'metal' 'reggae' 'triphop' 'blues' 'instrumental'
 'rusrock' 'dnb' 'türk' 'post' 'country' 'psychedelic' 'conjazz' 'indie'
 'posthardcore' 'local' 'avantgarde' 'punk' 'videogame' 'techno' 'house'
 'christmas' 'melodic' 'caucasian' 'reggaeton' 'soundtrack' 'singer' 'ska'
 'salsa' 'ambient' 'film' 'western' 'rap' 'beats' "hard'n'heavy"
 'progmetal' 'minimal' 'tropical' 'contemporary' 'new' 'soul' 'holiday'
 'german' 'jpop' 'spiritual' 'urban' 'gospel' 'nujazz' 'folkmetal'
 'trance' 'miscellaneous' 'anime' 'hardcore' 'progressive' 'korean'
 'numetal' 'vocal' 'estrada' 'tango' 'loungeelectronic' 'classicmetal'
 'dubstep' 'club' 'deep' 'southern' 'black' 'folkrock' 'fitness' 'french'
 'disco' 'religious' 'drum' 'extrememetal' 'türkçe' 'experimental' 'easy'
 'metalcore' 'modern' 'argentinetango' 'old' 'swing' 'breaks' 'eurofolk'
 'stone

## Prueba de hipótesis <a id='hypothesis'></a>

### Hipótesis: comparar el comportamiento del usuario o la usuaria en las dos ciudades <a id='activity'></a>

La hipótesis afirma que existen diferencias en la forma en que los usuarios y las usuarias de Springfield y Shelbyville consumen música. Para comprobar esto, se usan los datos de tres días de la semana: lunes, miércoles y viernes.

In [20]:
# Contar las canciones reproducidas en cada ciudad
print(df.groupby('city')['track'].count())

city
Shelbyville    18512
Springfield    42741
Name: track, dtype: int64


En shelbyville se reprodujeron 18512 canciones y en Springfield 42741

In [21]:
# Calcular las canciones reproducidas en cada uno de los tres días
print(df.groupby('day')['track'].count())

day
Friday       21840
Monday       21354
Wednesday    18059
Name: track, dtype: int64


 Se puede mostrar el numero de cancines escuchadas en cada dia de la semana

In [22]:
# Declarar la función number_tracks() con dos parámetros: day= y city=.

def number_tracks(day,city):

    # Almacena las filas del DataFrame donde el valor en la columna 'day' es igual al parámetro day=
    
    df_day=df[df['day']==day]

    # Filtra las filas donde el valor en la columna 'city' es igual al parámetro city=
    df_city=df_day[df_day['city']==city]

    # Extrae la columna 'user_id' de la tabla filtrada y aplica el método count()
    count=df_city['user_id'].count()

    # Devolve el número de valores de la columna 'user_id'
    print(count)
 

In [23]:
# El número de canciones reproducidas en Springfield el lunes
day='Monday'
city='Springfield'
number_tracks(day,city)


15740


In [24]:
# El número de canciones reproducidas en Shelbyville el lunes
day='Monday'
city='Shelbyville'
number_tracks(day,city)



5614


In [25]:
# El número de canciones reproducidas en Springfield el miércoles
day='Wednesday'
city='Springfield'
number_tracks(day,city)



11056


In [26]:
# El número de canciones reproducidas en Shelbyville el miércoles
day='Wednesday'
city='Shelbyville'
number_tracks(day,city)




7003


In [27]:
# El número de canciones reproducidas en Springfield el viernes
day='Friday'
city='Springfield'
number_tracks(day,city)



15945


In [28]:
# El número de canciones reproducidas en Shelbyville el viernes
day='Friday'
city='Shelbyville'
number_tracks(day,city)



5895


**Conclusiones**



Efectivamente, la actividad de los usuarios difiere dependiendo del dia y de la ciudad.

Al analizar los datos se puede concluir que Springfield tiene un mayor numero de usuarios en cualquiera de los tres dias


# Conclusiones <a id='end'></a>

* Springfield: Tiene un numero mucho mayor de usuarios, y los viernes es el dia que hay mas usuarios
* Shelbyville: El miercoles es el dia que tiene mayor numero de usuarios